#!/usr/bin/env bash
# Download GitHub Release binary + vosk-lib + model into one directory.
# Requires: bash, curl, unzip; jq for JSON (brew install jq / apt install jq).
# One self-contained folder (default ./localvox-light under current directory):
#   localvox-light  .env  vosk-lib/  models/
#
#   cd ~/apps && bash install-release.sh
#   ./localvox-light/localvox-light --tui
#
# One-liner:
#   curl -fsSL https://raw.githubusercontent.com/cascad/localvox-light/main/scripts/install-release.sh | bash
#
# Optional: --install-dir=~/lv --tag=v0.1.0 --repo=owner/repo --branch=main

set -euo pipefail

REPO="cascad/localvox-light"
TAG="latest"
BRANCH="main"
INSTALL_DIR="$(pwd)/localvox-light"

for a in "$@"; do
  case "$a" in
    --repo=*) REPO="${a#*=}" ;;
    --tag=*) TAG="${a#*=}" ;;
    --install-dir=*) INSTALL_DIR="${a#*=}" ;;
    --branch=*) BRANCH="${a#*=}" ;;
    --skip-vosk) SKIP_VOSK=1 ;;
    --skip-binary) SKIP_BINARY=1 ;;
    *)
      echo "Unknown arg: $a" >&2
      exit 1
      ;;
  esac
done

command -v curl >/dev/null || { echo "Need curl" >&2; exit 1; }
command -v unzip >/dev/null || { echo "Need unzip" >&2; exit 1; }
command -v jq >/dev/null || { echo "Need jq (parse GitHub API). Install: apt install jq / brew install jq" >&2; exit 1; }

mkdir -p "$INSTALL_DIR"
INSTALL_DIR="$(cd "$INSTALL_DIR" && pwd)"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if [ -z "${SKIP_VOSK:-}" ]; then
  echo "Fetching setup-vosk.sh (branch $BRANCH)..."
  curl -fsSL -A "localvox-light-install/1.0" \
    "https://raw.githubusercontent.com/$REPO/$BRANCH/scripts/setup-vosk.sh" \
    -o "$TMP/setup-vosk.sh"
  bash "$TMP/setup-vosk.sh" --install-root="$INSTALL_DIR"
fi

if [ -z "${SKIP_BINARY:-}" ]; then
  if [ "$TAG" = "latest" ]; then
    API="https://api.github.com/repos/$REPO/releases/latest"
  else
    API="https://api.github.com/repos/$REPO/releases/tags/$TAG"
  fi
  echo "Release API: $API"
  JSON="$(curl -fsSL -H "Accept: application/vnd.github+json" -A "localvox-light-install/1.0" "$API")"

  case "$(uname -s)" in
    Linux)
      case "$(uname -m)" in
        x86_64)
          URL="$(echo "$JSON" | jq -r '.assets[] | select(.name | test("x86_64-unknown-linux-gnu")) | .browser_download_url' | head -1)"
          ;;
        aarch64 | arm64)
          URL="$(echo "$JSON" | jq -r '.assets[] | select(.name | test("aarch64-unknown-linux-gnu")) | .browser_download_url' | head -1)"
          ;;
        *)
          echo "Unsupported Linux arch: $(uname -m)" >&2
          exit 1
          ;;
      esac
      ;;
    Darwin)
      case "$(uname -m)" in
        arm64)
          URL="$(echo "$JSON" | jq -r '.assets[] | select(.name | test("aarch64-apple-darwin")) | .browser_download_url' | head -1)"
          ;;
        *)
          URL="$(echo "$JSON" | jq -r '.assets[] | select(.name | test("x86_64-apple-darwin")) | .browser_download_url' | head -1)"
          ;;
      esac
      ;;
    *)
      echo "Use install-release.ps1 on Windows." >&2
      exit 1
      ;;
  esac

  if [ -z "$URL" ] || [ "$URL" = "null" ]; then
    echo "No matching asset. Assets in this release:" >&2
    echo "$JSON" | jq -r '.assets[].name' >&2 || true
    echo "Create a GitHub Release and upload binaries (names like CI artifacts)." >&2
    exit 1
  fi

  NAME="$(basename "$URL" | cut -d'?' -f1)"
  OUT="$TMP/$NAME"
  echo "Downloading $URL"
  curl -fsSL -A "localvox-light-install/1.0" -L "$URL" -o "$OUT"

  if [[ "$NAME" == *.zip ]]; then
    unzip -o -q "$OUT" -d "$INSTALL_DIR"
    BIN_PATH="$(find "$INSTALL_DIR" -type f \( -name 'localvox-light' -o -name 'localvox-light-*' \) ! -name '*.dll' 2>/dev/null | head -1)"
  else
    BIN_PATH="$INSTALL_DIR/$NAME"
    chmod +x "$OUT"
    cp -f "$OUT" "$BIN_PATH"
  fi
  if [ -z "${BIN_PATH:-}" ] || [ ! -f "$BIN_PATH" ]; then
    echo "No binary found under $INSTALL_DIR" >&2
    exit 1
  fi
  TARGET="$INSTALL_DIR/localvox-light"
  if [ "$BIN_PATH" != "$TARGET" ]; then
    rm -f "$TARGET"
    mv -f "$BIN_PATH" "$TARGET"
  fi
  chmod +x "$TARGET"

  MDL_FILE=""
  if [ -d "$INSTALL_DIR/models" ]; then
    MDL_FILE="$(find "$INSTALL_DIR/models" -type f -path '*/am/final.mdl' 2>/dev/null | head -1)"
  fi
  if [ -n "$MDL_FILE" ]; then
    MODEL_DIR="$(dirname "$(dirname "$MDL_FILE")")"
  else
    MODEL_DIR="$INSTALL_DIR/models/vosk-model-ru-0.42"
  fi

  cat >"$INSTALL_DIR/.env" <<EOF
# Generated by install-release.sh — edit LOCALVOX_LIGHT_MODEL if the model lives elsewhere.
LOCALVOX_LIGHT_MODEL=$MODEL_DIR
EOF

  echo ""
  echo "Bundle ready: $INSTALL_DIR"
  echo "Run: cd \"$INSTALL_DIR\" && ./localvox-light --tui"
fi
