# Portable bundle under ONE directory (default: .\localvox-light in current folder):
#   localvox-light.exe  .env  vosk-lib\  models\
# .env sets LOCALVOX_LIGHT_MODEL; the binary loads .env from its folder and prepends vosk-lib to PATH.
#
#   cd D:\apps
#   .\install-release.ps1
#   .\localvox-light\localvox-light.exe --tui
#
# One-liner (installs to .\localvox-light where you run it — cd first if needed):
#   cd $HOME\Desktop; $u='https://raw.githubusercontent.com/cascad/localvox-light/main/scripts/install-release.ps1'; $p="$env:TEMP\lv-install.ps1"; iwr -useb $u -OutFile $p; & $p
#
# Optional: -InstallDir D:\lv  -Tag v0.1.0  -Repo owner/repo  -Branch main  -SkipVosk  -SkipBinary
#
# setup-vosk.ps1 is fetched once to populate vosk-lib + models (same layout as dev).

param(
    [string]$InstallDir = "",
    [string]$Repo = "cascad/localvox-light",
    [string]$Tag = "latest",
    [string]$Branch = "main",
    [switch]$SkipVosk,
    [switch]$SkipBinary
)

$ErrorActionPreference = "Stop"
if ([string]::IsNullOrWhiteSpace($InstallDir)) {
    $InstallDir = Join-Path -Path (Get-Location).Path -ChildPath "localvox-light"
}

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
$InstallDir = (Resolve-Path -LiteralPath $InstallDir).Path

if (-not $SkipVosk) {
    $setupUrl = "https://raw.githubusercontent.com/$Repo/$Branch/scripts/setup-vosk.ps1"
    $tmpSetup = Join-Path $env:TEMP ("lv-setup-vosk-" + [Guid]::NewGuid().ToString() + ".ps1")
    Write-Host "Fetching $setupUrl"
    Invoke-WebRequest -Uri $setupUrl -OutFile $tmpSetup -UserAgent "localvox-light-install/1.0"
    try {
        & powershell -NoProfile -ExecutionPolicy Bypass -File $tmpSetup -InstallRoot $InstallDir
    } finally {
        Remove-Item -LiteralPath $tmpSetup -Force -ErrorAction SilentlyContinue
    }
}

if (-not $SkipBinary) {
    $api = if ($Tag -eq "latest") {
        "https://api.github.com/repos/$Repo/releases/latest"
    } else {
        "https://api.github.com/repos/$Repo/releases/tags/$Tag"
    }
    Write-Host "Release API: $api"
    $rel = Invoke-RestMethod -Uri $api -Headers @{ "User-Agent" = "localvox-light-install/1.0" }

    $patterns = @()
    if ($env:OS -eq "Windows_NT") {
        if ($env:PROCESSOR_ARCHITECTURE -eq "AMD64") {
            $patterns = @("*x86_64-pc-windows-msvc*", "*windows*x86_64*", "*.exe")
        } elseif ($env:PROCESSOR_ARCHITECTURE -eq "ARM64") {
            $patterns = @("*aarch64-pc-windows-msvc*", "*windows*arm64*", "*.exe")
        } else {
            $patterns = @("*win32*", "*.exe")
        }
    } else {
        throw "Use install-release.sh on non-Windows."
    }

    $assets = @($rel.assets)
    $asset = $null
    foreach ($pat in $patterns) {
        $asset = $assets | Where-Object { $_.name -like $pat } | Select-Object -First 1
        if ($asset) { break }
    }
    if (-not $asset) {
        Write-Host "Assets in this release:"
        $assets | ForEach-Object { Write-Host "  -" $_.name }
        throw "No matching Windows asset."
    }

    $outPath = Join-Path $InstallDir $asset.name
    Write-Host "Downloading" $asset.browser_download_url
    Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $outPath -UserAgent "localvox-light-install/1.0"

    if ($asset.name -like "*.zip") {
        Expand-Archive -Path $outPath -DestinationPath $InstallDir -Force
        Remove-Item -LiteralPath $outPath -Force
        $mainExe = Get-ChildItem -Path $InstallDir -Filter "localvox-light*.exe" -Recurse -File -ErrorAction SilentlyContinue |
            Select-Object -First 1
        if (-not $mainExe) {
            $mainExe = Get-ChildItem -Path $InstallDir -Filter "*.exe" -Recurse -File -ErrorAction SilentlyContinue |
                Select-Object -First 1
        }
    } else {
        $mainExe = Get-Item -LiteralPath $outPath
    }
    if (-not $mainExe) {
        throw "No .exe found in $InstallDir after download."
    }
    $targetExe = Join-Path $InstallDir "localvox-light.exe"
    if ($mainExe.FullName -ne $targetExe) {
        if (Test-Path -LiteralPath $targetExe) { Remove-Item -LiteralPath $targetExe -Force }
        Move-Item -LiteralPath $mainExe.FullName -Destination $targetExe -Force
    }

    $modelDir = Get-ChildItem -Path (Join-Path $InstallDir "models") -Directory -ErrorAction SilentlyContinue |
        Where-Object { Test-Path -LiteralPath (Join-Path $_.FullName "am\final.mdl") } |
        Select-Object -First 1
    if (-not $modelDir) {
        $modelAbs = Join-Path $InstallDir "models\vosk-model-ru-0.42"
        Write-Warning "Could not find models\*\am\final.mdl; .env uses default path: $modelAbs"
    } else {
        $modelAbs = $modelDir.FullName
    }

    $modelForEnv = ($modelAbs -replace '\\', '/')
    $envLines = @(
        "# Generated by install-release.ps1 — edit LOCALVOX_LIGHT_MODEL if the model lives elsewhere.",
        "LOCALVOX_LIGHT_MODEL=$modelForEnv",
        ""
    ) -join "`r`n"
    $envPath = Join-Path $InstallDir ".env"
    [System.IO.File]::WriteAllText($envPath, $envLines, [System.Text.UTF8Encoding]::new($false))

    Write-Host ""
    Write-Host "Bundle ready (everything under):"
    Write-Host "  $InstallDir"
    Write-Host "Run (from that folder, or double-click the exe):"
    Write-Host "  .\localvox-light.exe --tui"
}
